/*
 * This source file was generated by the Gradle 'init' task
 */
package cl.claveles.finanzas.adapter;

import cl.claveles.finanzas.adapter.dto.canonico.SocioCanonico;
import cl.claveles.finanzas.adapter.generado.ServiciosContabilidadYFinanzas;
import com.google.gson.Gson;
import jakarta.jms.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.YearMonth;

public class App {

    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        InitialContext jndi = null;
        try {
            jndi = new InitialContext();
            ConnectionFactory connectionFactory =
                    (ConnectionFactory) jndi.lookup("connFactoryBroker1");
            Topic origen  = (Topic) jndi.lookup("topicos/nuevosSocios");

            String brokerUsuario = "claveles";
            String brokerPassword = "Fundacion25..";
            try (
                    Connection connection = connectionFactory.createConnection(
                            brokerUsuario,
                            brokerPassword
                    )
            ) {
                String clienteId = "FinanzasAdapter";
                String nombreSuscripcion = "RegistroNuevosSociosEnFinanzas";
                connection.setClientID(clienteId);
                Session sesion = connection.createSession(Session.CLIENT_ACKNOWLEDGE);
                MessageConsumer consumer = sesion.createDurableConsumer(origen, nombreSuscripcion);

                LOGGER.info("Configurando MessageListener...");
                consumer.setMessageListener(new MessageListener() {
                    @Override
                    public void onMessage(Message mensaje) {
                        try {
                            var socio = jsonToObject(mensaje.getBody(String.class));
                            crearRegistrosEnSistemaFinanzas(
                                socio.datosPersonales().identificador(),
                                socio.datosPersonales().nombre(),
                                socio.aporte().diaPago(),
                                new BigDecimal(socio.aporte().montoMensual())
                            );
                            mensaje.acknowledge();
                        } catch (JMSException e) {
                            throw new RuntimeException(e);
                        }
                    }
                });

                connection.start();
                Thread.currentThread().join();
            } catch (InterruptedException e) {
                LOGGER.error("Error al mantener la aplicación en ejecución (Thread.join())", e);
                throw new RuntimeException(e);
            }
        } catch (NamingException | JMSException e) {
            throw new RuntimeException(e);
        } finally {
            if (jndi != null) {
                try {
                    jndi.close();
                } catch (NamingException fne) {
                    LOGGER.error("Problema al cerrar JNDI", fne);
                }
            }
        }
    }

    private static SocioCanonico jsonToObject(String jsonObj) {
        var gson = new Gson();
        return gson.fromJson(jsonObj, SocioCanonico.class);
    }

    private static void crearRegistrosEnSistemaFinanzas(
            String socioId,
            String socioNombre,
            int diaPago,
            BigDecimal montoCuota
            ) {
        var servicio = new ServiciosContabilidadYFinanzas().getServicioImplPort();
        servicio.crearSocio(socioId, socioNombre);
        LOGGER.info("servicio.crearSocio({}, {});", socioId, socioNombre);

        var hoy         = LocalDate.now();
        var diaDelMes   = hoy.getDayOfMonth();
        var primerMes   = hoy.getMonthValue();
        var anno        = hoy.getYear();

        if( diaDelMes > diaPago) {
            primerMes++;
        }

        for(int mes = primerMes; mes <= 12; mes++) {
            int diaPagoReal = diaPago;
            if( diaPago >= 31) {
                diaPagoReal = YearMonth.of(anno, mes).lengthOfMonth();
            }
            if ( diaPago > 28 && mes == 2) {
                diaPagoReal = YearMonth.of(anno, mes).lengthOfMonth();
            }
            LOGGER.info("Vencimiento: {}-{}-{}", anno, mes, diaPagoReal);

            try {
                var factory = DatatypeFactory.newInstance();
                var xmlDate = factory.newXMLGregorianCalendar(
                        anno, mes, diaPagoReal, 0, 0, 0, 0, 0
                );
                LOGGER.info("xmlDate: {}", xmlDate);
                servicio.crearCuotaPorCobrar(socioId, montoCuota, xmlDate);
                LOGGER.info("servicio.crearCuotaPorCobrar()");
                LOGGER.info("socioId={}", socioId);
                LOGGER.info("montoCuota={}", montoCuota);
                LOGGER.info("xmlDate={}", xmlDate);
            } catch (DatatypeConfigurationException e) {
                throw new RuntimeException(e);
            }
        }
    }
}
