package cl.claveles.finanzas.adapter.generado;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-01T22:43:24.154-03:00
 * Generated source version: 4.1.4
 *
 */
@WebService(targetNamespace = "http://finanzas.claveles.cl/", name = "Servicio")
@XmlSeeAlso({ObjectFactory.class})
public interface Servicio {

    @WebMethod
    @RequestWrapper(localName = "crearSocio", targetNamespace = "http://finanzas.claveles.cl/", className = "cl.claveles.finanzas.adapter.generado.CrearSocio")
    @ResponseWrapper(localName = "crearSocioResponse", targetNamespace = "http://finanzas.claveles.cl/", className = "cl.claveles.finanzas.adapter.generado.CrearSocioResponse")
    @WebResult(name = "socioId", targetNamespace = "")
    public java.lang.String crearSocio(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre
    );

    @WebMethod
    @RequestWrapper(localName = "crearCuotaPorCobrar", targetNamespace = "http://finanzas.claveles.cl/", className = "cl.claveles.finanzas.adapter.generado.CrearCuotaPorCobrar")
    @ResponseWrapper(localName = "crearCuotaPorCobrarResponse", targetNamespace = "http://finanzas.claveles.cl/", className = "cl.claveles.finanzas.adapter.generado.CrearCuotaPorCobrarResponse")
    @WebResult(name = "cuotaId", targetNamespace = "")
    public java.lang.String crearCuotaPorCobrar(

        @WebParam(name = "socioId", targetNamespace = "")
        java.lang.String socioId,
        @WebParam(name = "monto", targetNamespace = "")
        java.math.BigDecimal monto,
        @WebParam(name = "vencimiento", targetNamespace = "")
        java.lang.Object vencimiento
    );
}
