package cl.claveles.finanzas.adapter.generado;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-01T22:43:24.242-03:00
 * Generated source version: 4.1.4
 *
 */
@WebServiceClient(name = "ServiciosContabilidadYFinanzas",
                  wsdlLocation = "http://localhost:8080/soap/finanzas?wsdl",
                  targetNamespace = "http://finanzas.claveles.cl/")
public class ServiciosContabilidadYFinanzas extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://finanzas.claveles.cl/", "ServiciosContabilidadYFinanzas");
    public static final QName ServicioImplPort = new QName("http://finanzas.claveles.cl/", "ServicioImplPort");
    static {
        URL url = null;
        try {
            url = URI.create("http://localhost:8080/soap/finanzas?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiciosContabilidadYFinanzas.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/soap/finanzas?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiciosContabilidadYFinanzas(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiciosContabilidadYFinanzas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosContabilidadYFinanzas() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiciosContabilidadYFinanzas(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiciosContabilidadYFinanzas(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiciosContabilidadYFinanzas(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Servicio
     */
    @WebEndpoint(name = "ServicioImplPort")
    public Servicio getServicioImplPort() {
        return super.getPort(ServicioImplPort, Servicio.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Servicio
     */
    @WebEndpoint(name = "ServicioImplPort")
    public Servicio getServicioImplPort(WebServiceFeature... features) {
        return super.getPort(ServicioImplPort, Servicio.class, features);
    }

}
