/*
 * This source file was generated by the Gradle 'init' task
 */
package cl.claveles.xmladapter;

import cl.claveles.xmladapter.dto.Inscritos;
import cl.claveles.xmladapter.dto.Socio;
import jakarta.jms.*;
import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Marshaller;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.naming.InitialContext;
import javax.naming.NamingException;
import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    private static Marshaller marshaller;

    public static void main(String[] args) {
        try {
            //var xmlContent = Files.readString(Path.of("../../NuevosSocios-20251231.xml"));
            var xmlContent = Files.readString(Path.of(args[0]));

            JAXBContext contexto = JAXBContext.newInstance(Inscritos.class);
            var unmarshaller = contexto.createUnmarshaller();
            marshaller = contexto.createMarshaller();

            var reader = new StringReader(xmlContent);
            var inscritos = (Inscritos) unmarshaller.unmarshal(reader);
            enviarSociosACanalJMS(inscritos);
        } catch (IOException e) {
            LOGGER.error("No se pudo leer el archivo XML", e);
            throw new RuntimeException(e);
        } catch (JAXBException e) {
            LOGGER.error("Error durante el unmarshall", e);
            throw new RuntimeException(e);
        }
    }

    private static void enviarSociosACanalJMS(Inscritos inscritos) {
        InitialContext jndi = null;
        try {
            jndi = new InitialContext();
            ConnectionFactory connectionFactory = (ConnectionFactory) jndi.lookup("connFactoryBroker1");
            Destination destino = (Destination) jndi.lookup("colas/EnTerrenoNuevosSocios");

            String brokerUsuario  = "claveles";
            String brokerPassword = "Fundacion25..";
            try (Connection connection = connectionFactory.createConnection(brokerUsuario, brokerPassword) ) {
                Session sesion = connection.createSession();
                MessageProducer messageProducer = sesion.createProducer(destino);

                for(Socio s : inscritos.getSocios()) {
                    var writer = new StringWriter();
                    marshaller.marshal(s, writer);
                    String mensaje = writer.toString();
                    TextMessage textMessage = sesion.createTextMessage(mensaje);
                    messageProducer.send( textMessage );
                    LOGGER.info("Enviando mensaje a cola: "+mensaje);
                }
            } catch (JAXBException e) {
                LOGGER.error("Error al generar el XML", e);
                throw new RuntimeException(e);
            }
        } catch (NamingException | JMSException e) {
            LOGGER.error("Problema al intentar enviar el mensaje JMS", e);
            throw new RuntimeException(e);
        } finally {
            if(jndi != null) {
                try {
                    jndi.close();
                } catch (NamingException fne) {
                    LOGGER.error("Problema al cerrar JNDI", fne);
                }
            }
        }
    }

    private void currentDir() {
        Path currentPath = Paths.get("");
        String currentDirectory = currentPath.toAbsolutePath().toString();
        System.out.println("Directorio actual: " + currentDirectory);
    }
}
