/*
 * This source file was generated by the Gradle 'init' task
 */
package cl.claveles.mkt.adapter;

import cl.claveles.mkt.adapter.dto.canonico.SocioCanonico;
import cl.claveles.mkt.adapter.dto.mkt.ContactoDTO;
import com.google.gson.Gson;
import jakarta.jms.*;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.client.WebTarget;
import jakarta.ws.rs.core.MediaType;
import java.time.LocalDateTime;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        InitialContext jndi = null;
        try {
            jndi = new InitialContext();
            ConnectionFactory connectionFactory =
                (ConnectionFactory) jndi.lookup("connFactoryBroker1");
            Topic origen = (Topic) jndi.lookup("topicos/nuevosSocios");

            String brokerUsuario = "claveles";
            String brokerPassword = "Fundacion25..";
            try (
                Connection connection = connectionFactory.createConnection(
                    brokerUsuario,
                    brokerPassword
                )
            ) {
                String clienteId = "MarketingAdapter";
                String nombreSuscripcion = "RegistroNuevosSociosEnMkt";
                connection.setClientID(clienteId);
                Session sesion = connection.createSession(
                    Session.CLIENT_ACKNOWLEDGE
                );
                MessageConsumer consumer = sesion.createDurableConsumer(
                    origen,
                    nombreSuscripcion
                );

                LOGGER.info("Configurando MessageListener...");
                consumer.setMessageListener(
                    new MessageListener() {
                        @Override
                        public void onMessage(Message mensaje) {
                            try {
                                var socio = jsonToObject(
                                    mensaje.getBody(String.class)
                                );

                                crearRegistrosEnSistemaMarketing(socio);

                                mensaje.acknowledge();
                            } catch (JMSException e) {
                                throw new RuntimeException(e);
                            }
                        }
                    }
                );

                connection.start();
                Thread.currentThread().join();
            } catch (InterruptedException e) {
                LOGGER.error(
                    "Error al mantener la aplicación en ejecución (Thread.join())",
                    e
                );
                throw new RuntimeException(e);
            }
        } catch (NamingException | JMSException e) {
            throw new RuntimeException(e);
        } finally {
            if (jndi != null) {
                try {
                    jndi.close();
                } catch (NamingException fne) {
                    LOGGER.error("Problema al cerrar JNDI", fne);
                }
            }
        }
    }

    private static SocioCanonico jsonToObject(String jsonObj) {
        var gson = new Gson();
        return gson.fromJson(jsonObj, SocioCanonico.class);
    }

    private static ContactoDTO createContacto(
        String rut,
        String nombre,
        String apellido,
        String email,
        String telefono,
        String origen
    ) {
        var c = new ContactoDTO(nombre, apellido, email);
        c.setFechaRegistro(LocalDateTime.now());
        c.setId(rut);
        c.setTelefono(telefono);
        c.setEmpresa("");
        c.setOrigen(origen);
        c.setEstado("NUEVO");
        c.setNotas("");
        return c;
    }

    private static void crearRegistrosEnSistemaMarketing(SocioCanonico socio) {
        var baseUrl = "http://localhost:9052/api/contactos";

        WebTarget baseTarget;
        try (var cliente = ClientBuilder.newClient()) {
            baseTarget = cliente.target(baseUrl);
            var contacto = createContacto(
                socio.datosPersonales().identificador(),
                socio.datosPersonales().nombre(),
                "",
                "",
                socio.contacto().telefonos().getFirst().telefono(),
                ""
            );
            var respuesta = baseTarget
                .request(MediaType.APPLICATION_JSON_TYPE)
                .post(Entity.json(contacto));
            int estado = respuesta.getStatus();
            if (estado < 200 || estado >= 300) {
                String mensajeError = respuesta.readEntity(String.class);
                LOGGER.error("Estado respuesta: {}", estado);
                LOGGER.error("Respuesta: {}", respuesta);
                LOGGER.error("Error: {}", mensajeError);
                throw new RuntimeException(mensajeError);
            }
        }
    }
}
